---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

# Security (-sec)

- name: export custom attribute definitions
  include_tasks: exports/customattrs.yml
  vars:
    __ibm_infosvr_impexp_type: customattrs
    __ibm_infosvr_impexp_items: "{{ export.customattrs }}"
  when: >
        export.customattrs is defined
        and ('ibm-information-server-engine' in group_names)

- name: export common metadata (low-level)
  include_tasks: exports/istool.yml
  vars:
    __ibm_infosvr_impexp_type: common
    __ibm_infosvr_impexp_items: "{{ export.common }}"
    __ibm_infosvr_impexp_switch: "-cm"
  when: >
        export.common is defined
        and ('ibm-information-server-engine' in group_names)

- name: export logical data model metadata
  include_tasks: exports/one_type_with_conditions.yml
  vars:
    __ibm_infosvr_impexp_type: logical_data_model
    __ibm_infosvr_impexp_items: "{{ export.logicalmodel }}"
    __ibm_infosvr_impexp_switch: "-lm"
  when: >
        export.logicalmodel is defined
        and ('ibm-information-server-engine' in group_names)

- name: export physical data model metadata
  include_tasks: exports/one_type_with_conditions.yml
  vars:
    __ibm_infosvr_impexp_type: physical_data_model
    __ibm_infosvr_impexp_items: "{{ export.physicalmodel }}"
    __ibm_infosvr_impexp_switch: "-cm"
  when: >
        export.physicalmodel is defined
        and ('ibm-information-server-engine' in group_names)

- name: export database metadata
  include_tasks: exports/loop_included_objects.yml
  vars:
    __ibm_infosvr_impexp_type: database
    __ibm_infosvr_impexp_items: "{{ export.database }}"
    __ibm_infosvr_impexp_switch: "-cm"
  when: >
        export.database is defined
        and ('ibm-information-server-engine' in group_names)

- name: export data file metadata
  include_tasks: exports/one_type_with_conditions.yml
  vars:
    __ibm_infosvr_impexp_type: data_file
    __ibm_infosvr_impexp_items: "{{ export.datafile }}"
    __ibm_infosvr_impexp_switch: "-cm"
  when: >
        export.datafile is defined
        and ('ibm-information-server-engine' in group_names)

- name: export master data management model metadata
  include_tasks: exports/istool.yml
  vars:
    __ibm_infosvr_impexp_type: mdm
    __ibm_infosvr_impexp_items: "{{ export.mdm }}"
    __ibm_infosvr_impexp_switch: "-mdm"
  when: >
        export.mdm is defined
        and ('ibm-information-server-engine' in group_names)

- name: export data class metadata
  include_tasks: exports/one_type_with_conditions.yml
  vars:
    __ibm_infosvr_impexp_type: data_class
    __ibm_infosvr_impexp_items: "{{ export.dataclass }}"
    __ibm_infosvr_impexp_switch: "-dca"
  when: >
        export.dataclass is defined
        and ('ibm-information-server-engine' in group_names)

- name: export DataStage assets
  include_tasks: exports/loop_included_objects.yml
  vars:
    __ibm_infosvr_impexp_type: datastage
    __ibm_infosvr_impexp_items: "{{ export.datastage }}"
    __ibm_infosvr_impexp_switch: "-ds"
  when: >
        export.datastage is defined
        and ('ibm-information-server-engine' in group_names)

- name: export DataStage project variables
  include_tasks: exports/ds_vars.yml
  vars:
    __ibm_infosvr_impexp_type: ds_vars
    __ibm_infosvr_impexp_items: "{{ export.ds_vars }}"
  when: >
        export.ds_vars is defined
        and ('ibm-information-server-engine' in group_names)

## Reports (-rep)

- name: export Information Analyzer assets
  include_tasks: exports/loop_included_objects.yml
  vars:
    __ibm_infosvr_impexp_type: infoanalyzer
    __ibm_infosvr_impexp_items: "{{ export.infoanalyzer }}"
  when: >
        export.infoanalyzer is defined
        and ('ibm-information-server-engine' in group_names)

## FastTrack (-fasttrack)

- name: export extended data sources
  include_tasks: exports/loop_included_objects.yml
  vars:
    __ibm_infosvr_impexp_type: extendedsource
    __ibm_infosvr_impexp_items: "{{ export.extendedsource }}"
  when: >
        export.extendedsource is defined
        and ('ibm-information-server-engine' in group_names)

- name: export extension mapping documents
  include_tasks: exports/one_type_with_conditions.yml
  vars:
    __ibm_infosvr_impexp_type: extension_mapping_document
    __ibm_infosvr_impexp_items: "{{ export.extensionmap }}"
    __ibm_infosvr_impexp_switch: "-cm"
  when: >
        export.extensionmap is defined
        and ('ibm-information-server-engine' in group_names)

- name: export glossary metadata
  include_tasks: exports/loop_included_objects.yml
  vars:
    __ibm_infosvr_impexp_type: glossary
    __ibm_infosvr_impexp_items: "{{ export.glossary }}"
  when: >
        export.glossary is defined
        and ('ibm-information-server-engine' in group_names)

- name: export IGC metadata relationships
  include_tasks: exports/relationships.yml
  vars:
    __ibm_infosvr_impexp_type: relationships
    __ibm_infosvr_impexp_items: "{{ export.relationships }}"
  when: >
        export.relationships is defined
        and ('ibm-information-server-engine' in group_names)

- name: export operational metadata
  include_tasks: exports/omd.yml
  vars:
    __ibm_infosvr_impexp_type: omd
    __ibm_infosvr_impexp_items: "{{ export.omd }}"
  when: >
        export.omd is defined
        and ('ibm-information-server-engine' in group_names)
