---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

# Security (-sec)

- import_tasks: exports/export_cm_cadefs.yml
  when: ibm_infosvr_impexp_cm_cadefs_export is defined

- import_tasks: exports/export_cm.yml
  when: ibm_infosvr_impexp_cm_export is defined

- import_tasks: exports/export_lm.yml
  when: ibm_infosvr_impexp_lm_export is defined

- import_tasks: exports/export_mdm.yml
  when: ibm_infosvr_impexp_mdm_export is defined

- import_tasks: exports/export_dc.yml
  when: ibm_infosvr_impexp_dc_export is defined

- import_tasks: exports/export_datastage.yml
  when: ibm_infosvr_impexp_ds_export is defined

# Reports (-rep)

- import_tasks: exports/export_ia.yml
  when: ibm_infosvr_impexp_ia_export is defined

# FastTrack (-fasttrack)

- import_tasks: exports/export_xa.yml
  when: ibm_infosvr_impexp_xa_export is defined

- import_tasks: exports/export_xm.yml
  when: ibm_infosvr_impexp_xm_export is defined

- import_tasks: exports/export_glossary.yml
  when: ibm_infosvr_impexp_bg_export is defined

- import_tasks: exports/export_igc_relns.yml
  when: ibm_infosvr_impexp_igc_relns_export is defined
