---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: get nanosecond epoch
  command: date -u +%s%N
  register: __ibm_infosvr_impexp_epoch

- name: set date and time inputs
  set_fact:
    __ibm_infosvr_impexp_timestamp: "{{ '%Y%m%d_%H%M%S' | strftime(__ibm_infosvr_impexp_epoch.stdout[:-9]) }}"
    __ibm_infosvr_impexp_to_epoch: "{{ __ibm_infosvr_impexp_epoch.stdout[:-6] }}"
    cacheable: no

# Must be outside the 'include' below for privilege escalation to work
- name: ensure XML library is installed
  yum: name=python-lxml state=latest
  become: yes
  when: >
        ibm_infosvr_impexp_priv_escalate
        and not ('ibm-information-server-ug' in group_names)
        and not ('ibm-information-server-clients' in group_names)
        and gather is defined and gather
  tags:
    - envdetails

- name: retrieve environment details
  include_tasks: get_env_details.yml
  when: gather is defined and gather
  tags:
    - envdetails

- name: install prerequisite packages
  yum: state=latest name={{ item }}
  with_items:
    - python-requests
  become: yes
  when: >
          ibm_infosvr_impexp_priv_escalate
          and (export is defined or ingest is defined or progress is defined or validate is defined)
  tags:
    - export
    - ingest
    - progress
    - validate

- name: retrieve domain tier SSL certificate
  include_tasks: get_certificate.yml
  when: >
          ibm_infosvr_impexp_verify_selfsigned_ssl is defined
          and ibm_infosvr_impexp_verify_selfsigned_ssl
          and ('ibm-information-server-domain' in group_names)
          and (export is defined or ingest is defined or progress is defined or validate is defined)
  tags:
    - export
    - ingest
    - progress
    - validate

- name: add SSL certificate
  include_tasks: load_certificate.yml
  when: >
          ibm_infosvr_impexp_verify_selfsigned_ssl is defined
          and ibm_infosvr_impexp_verify_selfsigned_ssl
          and (export is defined or ingest is defined or progress is defined or validate is defined)
  tags:
    - export
    - ingest
    - progress
    - validate

# Must remain 'import' rather than 'include' to pass-through privilege escalation
- name: load mapping defaults (escalated)
  import_tasks: setup_mappings.yml
  become: yes
  when: >
          ibm_infosvr_impexp_priv_escalate
          and ('ibm-information-server-domain' in group_names)
          and (export is defined or ingest is defined or progress is defined or validate is defined)
  tags:
    - export
    - ingest
    - progress
    - validate

- name: load mapping defaults (un-escalated)
  include_tasks: setup_mappings.yml
  when: >
          ('ibm-information-server-domain' in group_names)
          and not ibm_infosvr_impexp_priv_escalate
          and (export is defined or ingest is defined or progress is defined or validate is defined)
  tags:
    - export
    - ingest
    - progress
    - validate

- name: export metadata
  include_tasks: export.yml
  when: export is defined
  tags:
    - export

- name: ingest metadata
  include_tasks: import.yml
  when: ingest is defined
  tags:
    - ingest

- name: progress workflow
  include_tasks: progress.yml
  when: >
          progress is defined
          and ('ibm-information-server-engine' in group_names)
  tags:
    - progress

- name: validate results
  include_tasks: validate.yml
  when: >
          validate is defined
          and ('ibm-information-server-engine' in group_names)

- name: remove SSL certificate
  include_tasks: remove_certificate.yml
  when: >
          ibm_infosvr_impexp_verify_selfsigned_ssl is defined
          and ibm_infosvr_impexp_verify_selfsigned_ssl
          and (export is defined or ingest is defined or progress is defined or validate is defined)
  tags:
    - export
    - ingest
    - progress
    - validate
