---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: update workflow state(s)
  igc_workflow:
    host: "{{ ibm_infosvr_impexp_services_host | lower }}"
    port: "{{ ibm_infosvr_impexp_services_console_port }}"
    user: "{{ ibm_infosvr_impexp_infosvr_admin_user }}"
    password: "{{ ibm_infosvr_impexp_infosvr_admin_user_pwd }}"
    asset_type: "{{ item.assets_of_type }}"
    from_state: "{% if item.with_options is defined %}\
                {{ item.with_options.from_state | default('ALL') }}\
                {% else %}\
                ALL\
                {% endif %}"
    action: "{{ item.using_action }}"
    comment: "{% if item.with_options is defined %}\
              {{ item.with_options.with_comment | default('') }}\
              {% endif %}"
    conditions: "{% if item.with_options is defined %}\
                {{ item.with_options.only_with_conditions | default([]) }}\
                {% else %}\
                []\
                {% endif %}"
    condition_join: "{% if item.with_options is defined %}\
                    {{ item.with_options.condition_join | default('AND') }}\
                    {% else %}\
                    AND\
                    {% endif %}"
    compared_to_published: "{% if item.with_options is defined %}\
                            {{ item.with_options.only_when_compared_to_published | default('') }}\
                            {% endif %}"
    batch: "{% if item.with_options is defined %}\
            {{ item.with_options.batch | default('100') }}\
            {% else %}\
            100\
            {% endif %}"
    cert: "{{ __ibm_infosvr_impexp_ssl_cert_location | default(omit) }}"
  register: __ibm_infosvr_impexp_workflow_updates
  with_items: "{{ progress }}"
  loop_control:
    label: "{{ item.assets_of_type }} - {{ item.using_action }}"

- debug:
    var: __ibm_infosvr_impexp_workflow_updates
    verbosity: 1
