---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: export extension mapping documents
  shell: >
          source ~/.bashrc &&
          . dsenv &&
          {{ ibm_infosvr_impexp_infosvr_install_location }}/Clients/istools/cli/istool.sh
          workbench extension mapping export
          -u {{ ibm_infosvr_impexp_infosvr_admin_user }}
          -p {{ ibm_infosvr_impexp_infosvr_admin_user_pwd }}
          -dom {{ ibm_infosvr_impexp_services_host | lower }}:{{ ibm_infosvr_impexp_services_console_port }}
          -pt '{{ outer_asset.name }}%'
          -dir /tmp/__export_{{ __ibm_infosvr_impexp_type }}_{{ outer_item.item.into | basename }}_tmp
          -o /tmp/__export_{{ __ibm_infosvr_impexp_type }}_{{ outer_item.item.into | basename }}.log
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_impexp_infosvr_install_location }}/Server/DSEngine"

- name: check for zip file
  stat: path=/tmp/__export_{{ __ibm_infosvr_impexp_type }}_{{ outer_item.item.into | basename }}_tmp/mapping_documents.zip
  register: __ibm_infosvr_impexp_xm_zip

- name: extract zip file
  unarchive:
    src: /tmp/__export_{{ __ibm_infosvr_impexp_type }}_{{ outer_item.item.into | basename }}_tmp/mapping_documents.zip
    dest: /tmp/__export_{{ __ibm_infosvr_impexp_type }}_{{ outer_item.item.into | basename }}_tmp/
    remote_src: yes
  when: __ibm_infosvr_impexp_xm_zip.stat.exists

- name: remove zip file
  file:
    path: /tmp/__export_{{ __ibm_infosvr_impexp_type }}_{{ outer_item.item.into | basename }}_tmp/mapping_documents.zip
    state: absent
  when: __ibm_infosvr_impexp_xm_zip.stat.exists
